import pygame.freetype

pygame.freetype.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_MIN_RADIUS = 20.0
ASTEROID_KINDS = 3
ASTEROID_LINE_WIDTH = 2
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_SIZE = 20.0
PLAYER_LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5.0
SHOT_LINE_WIDTH = 0

SCORE_BOX_FONT_SIZE = 12
FONT = pygame.freetype.Font(
    file="data/fonts/JetBrainsMonoNerdFont-Medium.ttf", size=SCORE_BOX_FONT_SIZE
)
SCORE_BOX_WIDTH = 150
SCORE_BOX_HEIGHT = 30
SCORE_BOX_X = SCREEN_WIDTH - SCORE_BOX_WIDTH - 10
SCORE_BOX_Y = 10
SCORE_BOX_BORDER_WIDTH = 1
SCORE_BOX_PADDING = 10

GAME_OVER_FONT_SIZE = 36
GAME_OVER_FONT = pygame.freetype.Font(
    file="data/fonts/JetBrainsMonoNerdFont-Medium.ttf", size=GAME_OVER_FONT_SIZE
)
GAME_OVER_BOX_BORDER_WIDTH = 2
GAME_OVER_BOX_PADDING = 20

# Colors
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GRAY = (100, 100, 100)
AZURE = (0, 127, 255)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)
